blueprint:
  name: 🔔 Alerte température basse (< 18°C)
  description: >
    Envoie une notification quand la température d'un capteur de type "temperature"
    descend sous un seuil défini. Ne se répète pas tant que la température n'est pas
    remontée au-dessus du seuil.
  domain: automation
  input:
    notify_device:
      name: Appareil de notification
      description: L'appareil ou le service qui recevra la notification
      selector:
        device:
          integration: mobile_app
          multiple: false
    seuil:
      name: Seuil de température
      description: En dessous de cette valeur, la notification est envoyée
      default: 18
      selector:
        number:
          min: 5
          max: 30
          unit_of_measurement: °C
          mode: slider

mode: parallel

trigger:
  - platform: state
    entity_id: all

condition:
  - condition: template
    value_template: >
      {% set s = trigger.to_state %}
      {% set seuil = blueprint.inputs.seuil | float(18) %}
      {{ s is not none
         and s.domain == 'sensor'
         and s.attributes.device_class == 'temperature'
         and (s.state | float(100) < seuil)
         and (trigger.from_state is none or trigger.from_state.state | float(100) >= seuil) }}

action:
  - variables:
      piece: "{{ area_name(trigger.entity_id) or state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
      t: "{{ trigger.to_state.state | float(0) }}"
      seuil: "{{ blueprint.inputs.seuil }}"
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    message: "🥶 {{ piece }} est à {{ '%.1f'|format(t) }}°C (sous {{ seuil }}°C)."
    title: "Alerte température"
