blueprint:
  name: 🔔 Alerte température basse (tous capteurs)
  description: >
    Notifie quand n'importe quel capteur de température passe sous le seuil.
    Une seule notif par descente, pas de répétition tant que la température
    de la pièce n'est pas repassée au-dessus du seuil.
  domain: automation
  input:
    seuil:
      name: Seuil de température (°C)
      default: 18
      selector:
        number:
          min: 5
          max: 30
          unit_of_measurement: °C
          mode: slider
    notify_devices:
      name: Appareils à notifier (mobile_app)
      description: Sélectionne un ou plusieurs appareils pour recevoir la notification
      selector:
        device:
          integration: mobile_app
          multiple: true

mode: parallel
max_exceeded: silent

trigger:
  - platform: state
    entity_id: all

condition:
  - condition: template
    value_template: >
      {% set s = trigger.to_state %}
      {% set f = trigger.from_state %}
      {% set seuil = (blueprint.inputs.seuil | float(18)) %}
      {{ s is not none
         and s.domain == 'sensor'
         and s.attributes.device_class == 'temperature'
         and s.state not in ['unknown','unavailable','None','nan']
         and (s.state | float(100) < seuil)
         and (
           f is none
           or f.state in ['unknown','unavailable','None','nan']
           or (f.state | float(100)) >= seuil
         ) }}

action:
  - variables:
      piece: "{{ area_name(trigger.entity_id) or state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
      t: "{{ trigger.to_state.state | float(0) }}"
      seuil: "{{ blueprint.inputs.seuil }}"
  - repeat:
      for_each: !input notify_devices
      sequence:
        - device_id: "{{ repeat.item }}"
          domain: mobile_app
          type: notify
          title: "Alerte température"
          message: "🥶 {{ piece }} est à {{ '%.1f'|format(t) }}°C (sous {{ seuil }}°C)."
